config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }

  resources 'categories', only: [:index, :show]
  resources 'products', only: [:index, :show]

  get 'cart' => 'carts#index', :as => 'cart_index'
  post 'cart' => 'carts#change_quantity'
  post 'cart/add/:id' => 'carts#add', :as => 'cart_add'
  delete 'cart/remove/:id' => 'carts#delete', :as => 'cart_delete'
  delete 'cart/empty' => 'carts#empty', :as => 'empty_cart'

  resources :orders, only: [:new] do
    collection do
      post 'checkout'
      get 'execute_payment'
    end
  end

  root to: 'products#index'
end

app/views/shared/_application_nav.html.slim
.row
  <!-- NavBar -->
  .container
    nav.navbar.sticky-top.navbar-expand-lg.navbar-light
      .container
        button.navbar-toggler.navbar-toggler-right type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
          span.navbar-toggler-icon
        = link_to 'ACV-Ecommerce',products_path  , class: 'navbar-brand'
        .collapse.navbar-collapse#navbarSupportedContent
          ul.nav.navbar-nav.mr-auto
            li.nav-item
              = link_to "PRODUCTS", products_path, class: 'nav-link'
            li.nav-item
              = link_to "CATEGORIES", categories_path, class: 'nav-link'
          ul.nav.navbar-nav.pull-right
            li.nav-item.dropdown
              a.dropdown-toggle.nav-link data-toggle="dropdown" href='#' aria-expanded="true"
                i.fa.fa-shopping-cart.fa-lg
              .dropdown-menu.dropdown-menu-right
                / - @cart.each do |key, val|
                /   = link_to "#{} x #{val}", product_path(key.to_i), class: 'dropdown-item'
                .dropdown-divider
                = link_to cart_path, class:'dropdown-item' do
                  i.fa.fa-check[aria-hidden="true"]  SHOW YOUR CART
            - if current_user
              li
                = link_to current_user.first_name, edit_user_registration_path, class: 'nav-link'
              li
                = link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link'
            - else
              li
                = link_to "Register", new_user_registration_path, class: 'nav-link'
              li
                = link_to "Login", new_user_session_path, class: 'nav-link'
  <!-- End NavBar  -->