config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }

  resources 'categories', only: [:index, :show]
  resources 'products', only: [:index, :show]

  get 'cart' => 'carts#index', :as => 'cart_index'
  post 'cart' => 'carts#change_quantity'
  post 'cart/add/:id' => 'carts#add', :as => 'cart_add'
  delete 'cart/remove/:id' => 'carts#delete', :as => 'cart_delete'
  delete 'cart/empty' => 'carts#empty', :as => 'empty_cart'

  resources :orders, only: [:new] do
    collection do
      post 'checkout'
      get 'execute_payment'
    end
  end

  root to: 'products#index'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  validates :name, :phone_number, :shipping_address, :email, :payment_id, presence: true
  after_initialize :shipping_details

  def shipping_details
    return if self.user.blank?
    self.name = name || user.first_name + ' ' + user.last_name
    self.phone_number = phone_number || user.phone
    self.email = email || user.email
    self.shipping_address = shipping_address || user.address
    self.note = note
  end

  def pay!
    self.pay_stt = true
    save
  end

  def get_order_items
    data = JSON.parse(self.data)
    products = Product.find(data.keys)
    order_items = {}
    products.each do |product|
      order_items[product] = data[product.id.to_s]
    end
    order_items
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CartsHelper
  include OrdersHelper

  before_action :authenticate_user!, only: [:index, :show]
  before_action :set_order, :set_payment, only: [:execute_payment, :show]
  before_action :check_cart, only: [:new, :checkout]

  def index
    @orders = current_user.orders.paginate(page: params[:page]).order(:created_at => :asc)
  end

  def new
    @order = Order.new(user: current_user)
    @order_items = get_cart_items
  end

  def checkout
    item_list = get_cart_items
    @payment = create_request_payment(item_list, execute_payment_orders_url, root_url)
    if @payment.create
      @order = Order.new(order_params.merge(user_id: current_user.try(:id),
                                            data: JSON(convert_cart_items_to_order_items(item_list)),
                                            total_amount: @total_price,
                                            payment_id: @payment.id))
      Order.transaction do
        if @order.save
          redirect_to @payment.links[1].href
        else
          raise ActiveRecord::Rollback
          flash[:error] = @order.errors.full_messages
          render :new
        end
      end
    else
      flash[:error] = @payment.error
      redirect_to root_url
    end
  end

  def show
    @order = Order.find(params[:order_id])
    @order_items = @order.get_order_items
    @mail_status = true
    OrderMailer.finished_order_email(@order).deliver_now rescue @mail_status = false
  end

  def execute_payment
    if @payment.execute(payer_id: params[:PayerID])
      @order.pay!
      flash.now[:success] = 'Execute payment successfully'
      @items = @order.get_order_items
      empty_cart
      render 'show'
    else
      flash[:error] = 'Execute payment fail'
      redirect_to root_path
    end
  end

  private

  def order_params
    params.require(:order).permit(:name, :phone_number, :shipping_address, :email)
  end

  def set_order
    @order = Order.find_by(payment_id: params[:paymentId], user: current_user)
    redirect_to root_path, notice: 'Order payment not found' if @order.blank?
  end

  def set_payment
    @payment = PayPal::SDK::REST::Payment.find(params[:paymentId])
  rescue StandardError
    redirect_to root_path, notice: 'Payment not found'
  end

  def check_cart
    if session[:cart].blank?
      flash[:warning] = 'Your cart is empty'
      redirect_to cart_index_path
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def create_request_payment(items, return_url, cancel_url)
    order_items = []
    calculate = 0
    items.each do |product, qtt|
      order_items << {
        name: product.name,
        sku: product.id.to_s,
        price: product.price.to_s,
        currency: 'USD',
        quantity: qtt['quantity']
      }
      calculate += product.price * qtt['quantity']
    end

    PayPal::SDK::REST::Payment.new(
      intent: 'sale',
      payer: {
        payment_method: 'paypal'
      },
      redirect_urls: {
        return_url: return_url,
        cancel_url: cancel_url
      },
      transactions: [{
        item_list: {
          items: order_items
        },
        amount: {
          total: calculate.to_s,
          currency: 'USD'
        },
        description: 'This is the payment transaction for your order from jientdongoc.'
      }]
    )
  end

  def convert_cart_items_to_order_items(items)
    h = {}
    items.each do |product, hash|
      h[product.id] = hash
    end
    h
  end
end

app/views/orders/_order_details.html.slim
h4.text-center SHIPPING DETAILS
= form_for(@order, url: checkout_orders_path, method: :post) do |f|
  .form-group
    = f.label 'Customer Name: '
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label 'Customer Phone Number: '
    = f.text_field :phone_number, class: 'form-control'
  .form-group
    = f.label 'Email: '
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label 'Shipping To: '
    = f.text_field :shipping_address, class: 'form-control'
  .form-group
    = f.label 'Note: '
    = f.text_area :note, class: 'form-control'
    p
      strong Total Price: $#{@total_price}
  .form-group
    = f.submit 'PayPal Checkout', class: 'btn btn-info'

app/views/orders/_order_items.html.slim
- product = item[0]
tr
  td
    = image_tag(product.img_url, size: "50")
    = link_to product.name, product_path(product.id)
  td = item[1]['quantity'].to_s
  td = number_to_currency (product.price), unit: '$'
  td = number_to_currency (item[1]['item_price']), unit: '$'

app/views/orders/new.html.slim
#order
  .row
    .col-md-7.order-item
      h4.text-center YOUR ORDERS
      .row.container
        table.table
          thead.thead-info
            tr
              th product
              th quantity
              th price
              th total
          tbody
            = render partial: 'order_items', collection: @order_items, as: :item
            tr
              td
              td
              td
              td = 'Total: $' + @total_price.to_s
    .col-md-5.order-shipping
      = render partial: 'order_details'

app/views/orders/show.html.slim
h3.text-center Here is Your order details
.container
  p id: #{@order.id}
  p Name: #{@order.name}
  p Phone number: #{@order.phone_number}
  p Shipping address: #{@order.shipping_address}
  p Total amount: $#{@order.total_amount}
  p Execute Payment: #{@order.pay_stt}
  p State Paypal Server Check: #{@payment.state}
  - if @payment.state == 'created'
    p But not pay yet
    = link_to 'PayPal Checkout Again', @payment.links[2].href, class: 'btn btn-info'