config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }

  resources 'categories', only: [:index, :show]
  resources 'products', only: [:index, :show]

  get 'cart' => 'carts#index', :as => 'cart_index'
  post 'cart' => 'carts#change_quantity'
  post 'cart/add/:id' => 'carts#add', :as => 'cart_add'
  delete 'cart/remove/:id' => 'carts#delete', :as => 'cart_delete'
  delete 'cart/empty' => 'carts#empty', :as => 'empty_cart'

  resources :orders, only: [:new] do
    collection do
      post 'checkout'
      get 'execute_payment'
    end
  end

  root to: 'products#index'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  before_save :check_data

  def check_data
    if data.blank?
      errors.add(:data, 'can\'t be blank')
      throw(:abort)
    end
    _data = JSON.parse(data)
    begin
      Product.where(_data.keys)
    rescue StandardError
      errors.add('cant find product id')
      throw(:abort)
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CartsHelper

  before_action :set_cart, except: [:empty]
  after_action :merge_cart_to_db, except: [:index, :empty]

  def index
    @cart_items = get_cart_items
  end

  def add
    quantity = params[:quantity].try(:to_i) || 1
    if !add_item?(params[:product_id], quantity)
      flash[:warning] = 'Invalid quantity'
    end
    redirect_to products_path
  end

  def delete
    session[:cart].delete(params[:id].to_s)
    flash[:success] = 'Delete item Successfully'
    redirect_to cart_index_path
  end

  def change_quantity
    if params[:quantity].blank? || params[:quantity].to_i < 1
      flash[:warning] = 'Quantity invalid'
    else
      session[:cart][params[:product_id]] = params[:quantity].to_i
    end
    redirect_to cart_index_path
  end

  def empty
    empty_cart
    flash[:success] = 'Your Cart is Empty'
    redirect_to cart_index_path
  end

  private
    def set_cart
      session[:cart] ||= {}
    end
end

app/helpers/carts_helper.rb
module CartsHelper
  def get_cart_items
    cart = session[:cart]
    product_data = {}
    if cart.present?
      products = Product.where(id: cart.keys)
      @total_price = 0
      products.each do |product|
        cart_item_price = cart[product.id.to_s] * product.price
        @total_price += cart_item_price
        product_data[product] = { 'quantity' => cart[product.id.to_s], 'item_price' => cart_item_price }
      end
    end
    product_data
  end

  def add_item?(product_id, quantity = 1)
    return false if quantity < 1 || Product.find_by(id: product_id).blank?
    if  session[:cart][product_id.to_s].present?
      session[:cart][product_id.to_s] += quantity
    else
      session[:cart][product_id.to_s] = quantity
    end
    true
  end

  def empty_cart
    session[:cart] = {}
    merge_cart_to_db
  end

  # When User Login and Logout
  def merge_data_from_db
    session[:cart] ||= {}
    begin
    session[:cart].merge!(JSON.parse(current_user.cart.data)) { |_key, oldval, newval| oldval + newval } if current_user.cart.data.present?
    rescue StandardError
      flash[:notice] = "Something went wrong!"
    end
    current_user.cart.data = JSON(session[:cart])
    current_user.cart.save!
  end

  def merge_cart_to_db
    if user_signed_in?
      if session[:cart]
        current_user.cart.data = JSON(session[:cart])
      end
      current_user.cart.save!
    end
  end
end

app/views/carts/index.html.slim
.cart
  .h2.text-center YOUR CART
  .row.container
    table.table
      thead.thead-info
        tr
          th product
          th name
          th quantity
          th price
          th total
          th delete
      tbody
        - @cart_items.each do |item|
          - product = item[0]
          tr
            td = image_tag(product.img_url, size: "100")
            td = link_to product.name, product_path(product.id)
            td
              = form_tag cart_path(product.id), method: :post do
                = hidden_field_tag :product_id, product.id
                = number_field_tag :quantity, item[1]['quantity'], min: 1, step: 1, style: "width: 100px"
                = submit_tag 'Change', class: 'btn btn-info btn-sm'
            td = number_to_currency (product.price), unit: '$'
            td = number_to_currency (item[1]['item_price']), unit: '$'
            td = link_to 'Delete', cart_delete_path(product.id), method: :delete
        tr
          td
          td
          td
          td
          td = 'Total: $' + @total_price.to_s
  .text-center
    = link_to 'Back', products_path, class: 'btn btn-primary'
    = link_to 'Order Now', new_order_path, class: 'btn btn-success'
    = link_to 'Remove all', empty_cart_path, method: :delete, class: 'btn btn-danger'