config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }

  resources 'categories', only: [:index, :show]
  resources 'products', only: [:index, :show]

  get 'cart' => 'carts#index', :as => 'cart_index'
  post 'cart' => 'carts#change_quantity'
  post 'cart/add/:id' => 'carts#add', :as => 'cart_add'
  delete 'cart/remove/:id' => 'carts#delete', :as => 'cart_delete'
  delete 'cart/empty' => 'carts#empty', :as => 'empty_cart'

  resources :orders, only: [:new] do
    collection do
      post 'checkout'
      get 'execute_payment'
    end
  end

  root to: 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, optional: true

  validates :name, :description, :img_url, presence: true
  validates :price, numericality: { greater_than: 0 }, presence: true 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.page(params[:page]).per(12)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/views/products/_product.html.slim
.col-sm-6.col-md-4.col-lg-4.mt-4
  .card
    = link_to product_path(product.id) do
      .img-box
        img.card-img-top src="#{product.img_url}" /
    .card-block
      .details
        = link_to product_path(product.id) do
          h5.card-title= product.name
        p= simple_format product.description.truncate(80)
      p.price= number_to_currency (product.price), unit: '$', precision: 2
      p
      = form_tag cart_add_path(product), method: :post,  id:'product-info' do
        = hidden_field_tag 'product_id', product.id
        fieldset.form-group.col-md-4
        = button_tag class: 'btn btn-addcart' do
          i.fa.fa-cart-plus.fa-lg
          | Add to Cart

app/views/products/index.html.slim
.products
  h2.title.text-center Products Listing
  .row
    = render partial: 'product', collection: @products
  = paginate @products

app/views/products/show.html.slim
.product
  .row.product-top
    .product-overview
      .col-md-4.product-img-left
        img.card-img-top src="#{@product.img_url}"
      .col-md-8.product-overview-right
        h2.product-name= @product.name
        br
        p
          = link_to products_path do
            span style="color:#1ac6ff" > Home
            | \
          = link_to '' do
            span style="color:#1ac6ff"
              = @product.name
            | \
        = form_tag cart_add_path, method: :post,  id:'product-info' do
          .product-text
            = simple_format @product.description
          hr
          .product-price
            h4= number_to_currency (@product.price), unit: '$', precision: 0
          = hidden_field_tag 'product_id', @product.id
          fieldset.form-groups.col-md-4
            = label_tag :quantity
            = number_field_tag :quantity, 1, min: 1, step: 1, class: 'form-control'
          = button_tag class: 'btn btn-addcart' do
            i.fa.fa-cart-plus.fa-lg
            | Add to Cart